# Generated by Django 5.0.14 on 2026-08-14 08:13

import django.db.models.deletion
import uuid
import vault.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.FileField(storage=vault.storage.ResourceStorage(), upload_to='')),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('UNSEARCHABLE', 'Unsearchable')], default='PROCESSING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('upvote_count', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subject')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='vault.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['subject'], name='vault_resou_subject_57d536_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['course'], name='vault_resou_course__369659_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_active'], name='vault_resou_is_acti_694eb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourceupvote',
            unique_together={('resource', 'user')},
        ),
    ]
