# Generated by Django 5.0.14 on 2026-08-14 09:18

import django.db.models.deletion
import uuid
import vault.models
from django.db import migrations, models


def create_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor != 'sqlite':
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


def drop_vector_extension(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_doubtboardcomment'),
    ]

    operations = [
        migrations.RunPython(create_vector_extension, reverse_code=drop_vector_extension),
        migrations.CreateModel(
            name='ResourceChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('page_number', models.IntegerField()),
                ('embedding', vault.models.CompatibleVectorField(dimensions=768)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='vault.resource')),
            ],
            options={
                'indexes': [vault.models.CompatibleHnswIndex(fields=['embedding'], name='resource_chunks_hnsw_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
