# Generated by Django 5.0.14 on 2026-08-14 08:38

import django.db.models.deletion
import market.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('REQUESTED', 'Requested'), ('GIVEN_AWAY', 'Given Away')], db_index=True, default='AVAILABLE', max_length=20)),
                ('photo_url', models.FileField(storage=market.storage.ListingStorage(), upload_to='')),
                ('pickup_area', models.TextField()),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used - Good', 'Used - Good'), ('Used - Fair', 'Used - Fair')], max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ListingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='market.listing')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='market.listing')),
            ],
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'is_active'], name='market_list_status_c8c1b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listingrequest',
            unique_together={('listing', 'requester')},
        ),
    ]
